PRG4_M6_P1_KEL6/Controllers/DataPetugasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRG4_M6_P1_KEL6.Models;

namespace PRG4_M6_P1_KEL6.Controllers
{
    public class DataPetugasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DataPetugasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DataPetugas
        public async Task<IActionResult> Index()
        {
              return _context.DataPetugas != null ? 
                          View(await _context.DataPetugas.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.DataPetugas'  is null.");
        }

        // GET: DataPetugas/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.DataPetugas == null)
            {
                return NotFound();
            }

            var dataPetuga = await _context.DataPetugas
                .FirstOrDefaultAsync(m => m.Nim == id);
            if (dataPetuga == null)
            {
                return NotFound();
            }

            return View(dataPetuga);
        }

        // GET: DataPetugas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DataPetugas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nim,Nama,Prodi,NoTelp,Status")] DataPetuga dataPetuga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dataPetuga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dataPetuga);
        }

        // GET: DataPetugas/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.DataPetugas == null)
            {
                return NotFound();
            }

            var dataPetuga = await _context.DataPetugas.FindAsync(id);
            if (dataPetuga == null)
            {
                return NotFound();
            }
            return View(dataPetuga);
        }

        // POST: DataPetugas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Nim,Nama,Prodi,NoTelp,Status")] DataPetuga dataPetuga)
        {
            if (id != dataPetuga.Nim)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dataPetuga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataPetugaExists(dataPetuga.Nim))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dataPetuga);
        }

        // GET: DataPetugas/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.DataPetugas == null)
            {
                return NotFound();
            }

            var dataPetuga = await _context.DataPetugas
                .FirstOrDefaultAsync(m => m.Nim == id);
            if (dataPetuga == null)
            {
                return NotFound();
            }

            return View(dataPetuga);
        }

        // POST: DataPetugas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.DataPetugas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DataPetugas'  is null.");
            }
            var dataPetuga = await _context.DataPetugas.FindAsync(id);
            if (dataPetuga != null)
            {
                _context.DataPetugas.Remove(dataPetuga);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataPetugaExists(string id)
        {
          return (_context.DataPetugas?.Any(e => e.Nim == id)).GetValueOrDefault();
        }
    }
}

PRG4_M6_P1_KEL6/Controllers/PengumumenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PRG4_M6_P1_KEL6.Models;

namespace PRG4_M6_P1_KEL6.Controllers
{
    public class PengumumenController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PengumumenController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pengumumen
        public async Task<IActionResult> Index()
        {
              return _context.Pengumumen != null ? 
                          View(await _context.Pengumumen.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Pengumumen'  is null.");
        }

        // GET: Pengumumen/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pengumumen == null)
            {
                return NotFound();
            }

            var pengumuman = await _context.Pengumumen
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pengumuman == null)
            {
                return NotFound();
            }

            return View(pengumuman);
        }

        // GET: Pengumumen/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pengumumen/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaPengumuman,JenisPengumuman,IsiPengumuman")] Pengumuman pengumuman)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pengumuman);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pengumuman);
        }

        // GET: Pengumumen/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pengumumen == null)
            {
                return NotFound();
            }

            var pengumuman = await _context.Pengumumen.FindAsync(id);
            if (pengumuman == null)
            {
                return NotFound();
            }
            return View(pengumuman);
        }

        // POST: Pengumumen/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaPengumuman,JenisPengumuman,IsiPengumuman")] Pengumuman pengumuman)
        {
            if (id != pengumuman.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pengumuman);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PengumumanExists(pengumuman.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pengumuman);
        }

        // GET: Pengumumen/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pengumumen == null)
            {
                return NotFound();
            }

            var pengumuman = await _context.Pengumumen
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pengumuman == null)
            {
                return NotFound();
            }

            return View(pengumuman);
        }

        // POST: Pengumumen/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pengumumen == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pengumumen'  is null.");
            }
            var pengumuman = await _context.Pengumumen.FindAsync(id);
            if (pengumuman != null)
            {
                _context.Pengumumen.Remove(pengumuman);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PengumumanExists(int id)
        {
          return (_context.Pengumumen?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PRG4_M6_P1_KEL6/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using PRG4_M6_P1_KEL6.Models;

namespace PRG4_M6_P1_KEL6.Controllers
{
    public class UsersController : Controller
    {
        private readonly Users _anggotaRepository;

        public UsersController(IConfiguration configuration)
        {
            _anggotaRepository = new Users(configuration);
        }
        public IActionResult Index(User anggotaModel)
        {
            anggotaModel = new User();

            string serializedModel = HttpContext.Session.GetString("Identity");

            if (serializedModel == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                anggotaModel = JsonConvert.DeserializeObject<User>(serializedModel);
            }

            /*ViewBag.UserRole = anggotaModel.peran;*/
            return View(_anggotaRepository);
        }

        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
              return _context.Users != null ? 
                          View(await _context.Users.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Users'  is null.");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nama,Username,Password,Alamat,NoTelp,Status")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nama,Username,Password,Alamat,NoTelp,Status")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

PRG4_M6_P1_KEL6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>Musholla Asy-Syabab</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="~/PRG4_M6_P1_KEL6.styles.css"
          asp-append-version="true" />

    <!-- base:css -->
    <link rel="stylesheet"
          href="~/template/vendors/typicons.font/font/typicons.css" />
    <link rel="stylesheet"
          href="~/template/vendors/css/vendor.bundle.base.css" />
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet"
          href="~/template/css/vertical-layout-light/style.css" />
    <!-- endinject -->
    <link rel="shortcut icon" href="~/template/images/favicon.png" />
    <link rel="stylesheet"
          href="~/template/vendors/font-awesome/css/font-awesome.min.css" />
</head>
<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo" >
                    <img src="~/template/images/logo.png" alt="logo" />
                </a>
                <a class="navbar-brand brand-logo-mini" href="index.html">
                    <img src="~/template/images/logo-mini.svg" alt="logo" />
                </a>
                <button class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex"
                        type="button"
                        data-toggle="minimize">
                    <span class="typcn typcn-th-menu"></span>
                </button>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <ul class="navbar-nav navbar-nav-right">
                    <li class="nav-item nav-profile dropdown">
                        <a class="nav-link dropdown-toggle pl-0 pr-0"
                           href="#"
                           data-toggle="dropdown"
                           id="profileDropdown">
                            <i class="typcn typcn-user-outline mr-0"></i>
                            <span class="nav-profile-name">Musholla Asy-Syabab</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right navbar-dropdown"
                             aria-labelledby="profileDropdown">
                            <a class="dropdown-item">
                                <i class="typcn typcn-cog text-primary"></i>
                                Settings
                            </a>
                            <a class="dropdown-item">
                                <i class="typcn typcn-power text-primary"></i>
                                Logout
                            </a>
                        </div>
                    </li>
                </ul>
                <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center"
                        type="button"
                        data-toggle="offcanvas">
                    <span class="typcn typcn-th-menu"></span>
                </button>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_settings-panel.html -->
            <div class="theme-setting-wrapper">
                <div id="settings-trigger">
                    <i class="typcn typcn-cog-outline"></i>
                </div>
                <div id="theme-settings" class="settings-panel">
                    <i class="settings-close typcn typcn-delete-outline"></i>
                    <p class="settings-heading">SIDEBAR SKINS</p>
                    <div class="sidebar-bg-options" id="sidebar-light-theme">
                        <div class="img-ss rounded-circle bg-light border mr-3"></div>
                        Light
                    </div>
                    <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                        <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                        Dark
                    </div>
                    <p class="settings-heading mt-2">HEADER SKINS</p>
                    <div class="color-tiles mx-0 px-4">
                        <div class="tiles success"></div>
                        <div class="tiles warning"></div>
                        <div class="tiles danger"></div>
                        <div class="tiles primary"></div>
                        <div class="tiles info"></div>
                        <div class="tiles dark"></div>
                        <div class="tiles default border"></div>
                    </div>
                </div>
            </div>
            <!-- partial -->
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <div class="d-flex sidebar-profile">
                            <div class="sidebar-profile-image">
                                <img src="~/template/images/faces/face29.png" alt="image" />
                                <span class="sidebar-status-indicator"></span>
                            </div>
                            <div class="sidebar-profile-name">
                                <p class="sidebar-name">Admin</p>
                                <p class="sidebar-designation">Welcome</p>
                            </div>
                        </div>
                        <div class="nav-search">
                            <div class="input-group">
                                <input type="text"
                                       class="form-control"
                                       placeholder="Type to search..."
                                       aria-label="search"
                                       aria-describedby="search" />
                                <div class="input-group-append">
                                    <span class="input-group-text" id="search">
                                        <i class="typcn typcn-zoom"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <p class="sidebar-menu-title">Dashboard</p>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="" asp-action="">
                            <i class="typcn typcn-device-desktop menu-icon"></i>
                            <span class="menu-title">Dashboard</span>
                        </a>
                        <p class="sidebar-menu-title">Master</p>
                    </li>
                    <li class="nav-item" >
                        <a class="nav-link" asp-controller="Users" asp-action="Index">
                            <i class="typcn typcn-device-desktop menu-icon"></i>
                            <span class="menu-title">Pengguna</span>
                        </a>
                    </li>
                    <li class="nav-item" >
                        <a class="nav-link" asp-controller="Pengumumen" asp-action="Index">
                            <i class="typcn typcn-device-desktop menu-icon"></i>
                            <span class="menu-title">Pengumuman</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="DataPetugas" asp-action="Index">
                            <i class="typcn typcn-device-desktop menu-icon"></i>
                            <span class="menu-title">Petugas</span>
                        </a>
                        <p class="sidebar-menu-title">Transaksi</p>
                    </li>
                    <li class="nav-item" >
                        <a class="nav-link" asp-controller="JadwalPetugas" asp-action="Index">
                            <i class="typcn typcn-device-desktop menu-icon"></i>
                            <span class="menu-title">Jadwal Petugas</span>
                        </a>
                    </li>
                </ul>
            </nav>
            <div class="container">
                <main role="main" class="pb-3">@RenderBody()</main>
            </div>
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->
    <!-- base:js -->
    <script src="~/template/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page-->
    <!-- End plugin js for this page-->
    <!-- inject:js -->
    <script src="~/template/js/off-canvas.js"></script>
    <script src="~/template/js/hoverable-collapse.js"></script>
    <script src="~/template/js/template.js"></script>
    <script src="~/template/js/settings.js"></script>
    <script src="~/template/js/todolist.js"></script>
    <!-- endinject -->
    <!-- plugin js for this page -->
    <script src="~/template/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/template/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page-->
    <script src="~/template/js/dashboard.js"></script>
    <!-- End custom js for this page-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>